spring:
    application:
        name: game-api-service
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
        show-sql: 'true'
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mariadb://52.199.126.208:3306/universe?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
        driverClassName: org.mariadb.jdbc.Driver
        username: root
        password: lukyluke
        hikari:
            pool-name: maria-db-pool
            maximum-pool-size: 10
            minimum-idle: 5
            max-lifetime: 600000
    cache:
        ehcache:
            config: classpath:ehcache.xml

reflectoring:
    trace: true

springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        path: /docs
        operationsSorter: method
        disable-swagger-default-url: true

server:
    port: '8080'
    servlet:
        context-path: /api/v1
jwt:
    secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength
    ext: 604800
    iteration: 33
    keylength: 256
    refreshExt: 604800
