spring:
    application:
        name: gateway-zuul
    cloud:
        gateway:
            routes:
                -   id: game_api-route
                    uri: http://localhost:8200
                    predicates:
                        - Path=/api/**
server:
    port: '8761'

jwt:
    secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength
    ext: 28800
    iteration: 33
    keylength: 256

