spring:
    application:
        name: gateway-zuul
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
        show-sql: 'true'
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mariadb://125.212.225.166:3306/universe?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
        driverClassName: org.mariadb.jdbc.Driver
        username: db_cluster
        password: bccs3_maria
        hikari:
            pool-name: maria-db-pool
            maximum-pool-size: 10
            minimum-idle: 5
            max-lifetime: 600000
    cache:
        ehcache:
            config: classpath:ehcache.xml
    cloud:
        gateway:
            routes:
                - id: game-api-route
                  uri: http://game-api-service:8200
                  predicates:
                      - Path=/api/**

server:
    port: '8761'

jwt:
    secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength
    ext: 28800
    iteration: 33
    keylength: 256

