version: "3.7"

services:
    gateway:
        image: gateway-service:1.0
        ports:
            - "8761:8761"
        environment:
            SPRING_DATASOURCE_URL: jdbc:mariadb://localhost:3306/universe?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
            SPRING_DATASOURCE_PASSWORD: lukyluke
            SPRING_DATASOURCE_USERNAME: root
            SPRING_PROFILES_ACTIVE: "prod"
            SPRING_APPLICATION_NAME: gateway-service
            SERVER_PORT: 8761
            ZUUL_HOST_CONNECT-TIMEOUT-MILLIS: 130000
            ZUUL_HOST_SOCKET-TIMEOUT-MILLIS: 130000
            HYSTRIX_COMMAND_DEFAULT_EXECUTION_ISOLATION_THREAD-TIMEOUTINMILLISECONDS: 120000
        deploy:
            replicas: 1
    game-api:
        image: game-api:1.0
        ports:
            - "8200:8080"
        environment:
            SPRING_DATASOURCE_URL: jdbc:mariadb://localhost:3306/universe?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
            SPRING_DATASOURCE_PASSWORD: lukyluke
            SPRING_DATASOURCE_USERNAME: root
            SPRING_PROFILES_ACTIVE: "prod"
            SPRING_APPLICATION_NAME: game-api-service
            SERVER_PORT: 8080
            ZUUL_HOST_CONNECT-TIMEOUT-MILLIS: 130000
            ZUUL_HOST_SOCKET-TIMEOUT-MILLIS: 130000
            HYSTRIX_COMMAND_DEFAULT_EXECUTION_ISOLATION_THREAD-TIMEOUTINMILLISECONDS: 120000
        deploy:
            replicas: 1

    admin-service:
        image: admin-service:1.0
        ports:
            - "8000:8080"
        environment:
            SPRING_DATASOURCE_URL: jdbc:mariadb://localhost:3306/universe?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
            SPRING_DATASOURCE_PASSWORD: lukyluke
            SPRING_DATASOURCE_USERNAME: root
            SPRING_PROFILES_ACTIVE: "dev"
            SPRING_APPLICATION_NAME: game-api-service
            SERVER_PORT: 8080
            ZUUL_HOST_CONNECT-TIMEOUT-MILLIS: 130000
            ZUUL_HOST_SOCKET-TIMEOUT-MILLIS: 130000
            HYSTRIX_COMMAND_DEFAULT_EXECUTION_ISOLATION_THREAD-TIMEOUTINMILLISECONDS: 120000
        deploy:
            replicas: 1
